config/routes.rb
Library::Application.routes.draw do
  devise_for :users

 resources :books
 resources :reminders, only: [:create]
 resources :categories, only: [:show]

  scope :controller  => :books do
    get 'index'
    get 'searchbook'
    get 'results'
  end

  scope :controller => :members do
    get 'my_books'

  end

  scope :controller => :search do
    get 'index'

  end

  match 'categories/:name' => 'categories#show'
  resources :categories, :only [:show]

 

  authenticated :user do
    root :to => 'books#index'
  end

   root :to => 'main#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :reminders
  attr_accessible :author, :bookname, :image, :description, :checked_out, :user_id, :category_id, :remind_me, :avatar
  
  has_attached_file :avatar, :styles => { :medium => "152x200#", :thumb => "100x100#" }

after_save :reminder_mailer

def reminder_mailer
  if !self.checked_out && self.changes[:user_id] && self.user.nil?
  	# get all users waiting for a remind on this book
  	@users = self.reminders.map(&:user)
  	@users.inspect
  	@users.each do |user|
    ReminderMailer.remind_email(user).deliver
    end
    # remove reminders as users have been reminded
    self.reminders.destroy_all
  end
end

#Different Notice message depenedent upon Check In or Check out
def check_message
  self.checked_out ? 'You have checked out the book' : 'You have checked the book back in'
end


#Search books by name
def self.search(search)
  if search
    find(:all, :conditions => ['bookname LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
end



#Scopes
#scope :checked_out_book, where(:user_id => current_user.id && :checked_out => true)
scope :member_book, lambda{|user| { :conditions => { :user_id => user.id, :checked_out => true } } }
#scope :member_book, lambda {|user| where(:user_id => user.id, :checked_out => true) }
end

app/models/books.rb
class Books < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :books

  attr_accessible :name
  # attr_accessible :title, :body

  def self.categories_list
  joins(:books).
  select('categories.id, categories.name, count(*) AS books_count').
  group('categories.id, categories.name').
  order('books_count DESC')
  end

def self.user_categories_list(user)
  joins(:books).
  where('books.user_id = ?', user.try(:id) || user).
  select('categories.id, categories.name, count(*) AS books_count').
  group('categories.id, categories.name').
  order('books_count DESC')
end
  
end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
	belongs_to :user
	belongs_to :book
  attr_accessible :user_id, :book_id
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :books
  has_many :reminders
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin, :name, :book_id, :reminder_id
  # attr_accessible :title, :body
  
  def is_admin?
   self.admin == 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

def authenticate_admin_user!
  authenticate_user!
  unless current_user.admin?
    flash[:alert] = "This area is restricted to administrators only."
    redirect_to root_path
  end
end
 
def current_admin_user
  return nil if user_signed_in? && !current_user.admin?
  current_user
end

def after_sign_in_path_for(resource)
  if current_user.admin?
  searchbook_path

  else
     root_path
  end
end

end

app/controllers/book_controller.rb
class BookController < ApplicationController
  before_filter :authenticate_admin_user!
	include Book::BookFinder

	def searchbook
     
 
  end

  def results
   results = book_search(params[:search])
   @results = results
   @book = Book.new
   @book.author = results[0]["artistName"]

  end

def create
  @book = Book.new(params[:book])
  if @book.save
    redirect_to @book, notice: 'Book was successfully saved'
  else
    render action:new
  end
end

  def savebook

  Book.create(:author => response["results"]["artistName"])

  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :authenticate_admin_user!, :except => ['index', 'show', 'update']
  include Book::BookFinder

  def index
   @books = Book.all
   @books = Book.search(params[:search])
   @bookcategories = Category.categories_list

  end

  def show
   @book = Book.find(params[:id])
   @reminder = Reminder.new
   @bookcategories = Category.categories_list
  end

  def update
    @book = Book.find(params[:id])

     if @book.update_attributes(params[:book]) 
      redirect_to books_path, :notice => @book.check_message
     else
      render :action => 'show'
     end
  end


  def results
   results = book_search(params[:search])
   @results = results
   @book = Book.new
   unless @results.empty? or @results.nil? 
   @book.author = results.first["artistName"]
   @book.bookname = results.first["trackName"]
   @book.image = results.first["artworkUrl100"].gsub("100x100-75.jpg", "200x200-75.jpg")
   @book.description = results.first["description"]
   puts @results
 end
  end

def create
  @book = Book.new(params[:book])
  if @book.save
    redirect_to searchbook_path, notice: 'Book was successfully saved'
  else
    render :action => 'results'
  end
end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, :notice => "Successfully Deleted Book"
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def show
    @category = Category.where(:name => params[:id]).first
    @categorisedbooks = @category.books #get me all books that have the category name
  end

  
end

app/controllers/main_controller.rb
class MainController < ApplicationController

	def index

	end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  
  def my_books
    @book = Book.member_book(current_user)
    @mycategories = Category.user_categories_list(current_user)
    #@book = current_user.books.where(checked_out: true)
  end

 
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController

	def create

		@reminder = Reminder.new(params[:reminder])
		if @reminder.save
			redirect_to books_path, notice: 'Reminder has been set'
		end
end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def index

	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def remove_tags(object)
		toberemoved = ["<p>", "</p>", "<b>", "</b>", "<i>", "</i>", "<ul>", "</ul>", "<li>", "</li>", "<br />", "&nbsp;"]
		object.gsub(Regexp.union(toberemoved), '')
  end

  def login_status
    if current_user
      link_to "Sign Out", destroy_user_session_path, confirm: 'Are you sure you want to logout?', :method => :delete 
    end
  end

  def create_account 
    if !current_user
      link_to "Create Account", new_registration_path(resource_name)
    end
  end

  def all_books
    if current_user 
      link_to "All Books", books_path
    end
  end

  def my_books
    if current_user
      link_to "My Books", my_books_path
    end
  end

  def add_books
    if current_user
      link_to "Add Books", searchbook_path
    end
  end

  def image_choice
    if @book.image 
      tag("img", :src => @book.image )
    else
      image_tag @book.avatar.url(:medium)
    end
  end

  
end

app/helpers/book_helper.rb
module BookHelper

	
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/book/results.html.erb
<div class="container">
	<div class="row">
		<div class="span8 offset2">
			<% if @results.empty? %>
        <h1 class="resultTitle">sorry we can't find anything for that book.</h1>
         <%= link_to "Back To Search", root_path, :class => 'backButton' %>
      <% end %>


			<%= @results.first["trackName"] %> <br>
			 <img src =<%= @results.first["artworkUrl100"] %>> <br>
			  <%= @results.first["artistName"] %> <br>
			   <%= truncate(remove_tags(@results.first["description"]), :length => 250) %> <br>

		</div>
	</div>
</div>

<%= form_for @book do |f| %>
  <%= f.hidden_field :author %>
 
  <%= f.submit 'Save book' %>
<% end %>


app/views/book/searchbook.html.erb
<div class="container">
	<div class="row">
		<div class="span8 offset2">
			<%= form_tag results_path, :method => "get" do %>
			<%= text_field_tag 'search', nil, :placeholder => "Enter ISBN Number here...." %>
			<%= submit_tag 'Search' %>

			<% end %>
			


		</div>
	</div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="row">
        <div id="left-menu" class="span3">
          <div class="side-nav sidebar-block">
           <h2>Categories</h2>
            <ul>
              <% @bookcategories.each do |b| %>
              <li><%= link_to b.name, category_path(b.name) %></li>
             <% end %>
            </ul>
          </div>
        </div>
        <div class="span9">
          <%= form_tag books_path, :id => 'searchForm', :method => 'get' do  %>
          <%= text_field_tag :search, params[:search], :placeholder => "Enter a Book Name Here...." %>
          <%= submit_tag "Search", :type => :image, :src => '/assets/searchicon.png' %>
          <% end %>
        <div class="row">
          <% @books.each do |b| %>
           <div class= "span3 allBooks">
            <p><%= link_to truncate(b.bookname, :length => 33), b %></p>
            <% if b.image %>
             <img class="allBooksCover" src =<%= b.image %>>
             <% else %>
             <%= image_tag b.avatar.url(:medium), :class=> "allBooksCover" %>
            <% end %>
           </div><!--span3-->
          <% end %>
        </div>
      </div>



      </div>
    </div>
  </div>
</div>

    

app/views/books/results.html.erb
<div class="container">
 <div class="row">
  <div class="span8 offset2 addBook">
   <% if @results.empty? %>
    <h2>Sorry we can't find anything for that book.</h2>
    <h2> You May add the Book Manually</h2>

    <%= form_for @book, :html => {:id => 'addBookManual'} do |f| %>
    <%= f.label :bookname, 'Name of Book' %>
    <%= f.text_field :bookname %><br>
    <%= f.label :author, 'Name of Author' %>
    <%= f.text_field :author %><br>
    <%= f.label :category_id, "Category" %>
    <%= f.collection_select(:category_id, Category.all, :id, :name, :prompt => 'Please select a Category') %><br>
    <%= f.label :description, 'Brief Description',:id => 'descrip' %>
    <%= f.text_area :description, :size => "10x5" %><br>
    <%= f.label :avatar, 'Add Image' %>
    <%= f.file_field :avatar %><br>
    <%= f.submit 'Submit', :class => 'button' %>



    <% end %>
   <% else %>
    <%= @results.first["trackName"] %> <br>
    <img src =<%= @results.first["artworkUrl100"] %>> <br>
    <%= @results.first["artistName"] %> <br>
    <%= truncate(remove_tags(@results.first["description"]), :length => 250) %> <br>

    <%= form_for @book do |f| %>
    <%= f.label :category_id, "Category" %>
    <%= f.collection_select(:category_id, Category.all, :id, :name, :prompt => 'Please select a Category') %>
    <%= f.hidden_field :author %>
    <%= f.hidden_field :bookname %>
    <%= f.hidden_field :image %>
    <%= f.hidden_field :description %> 
  <%= f.submit 'Save book' %>
 <% end %>
<% end %>
  </div>
 </div>
</div>

app/views/books/searchbook.html.erb
<div class="container">
 <div class="row">
  <div class="span6 offset3">
    <h2>Add Books to your Library Here</h2>
   <%= form_tag results_path, :id => 'addBook', :method => "get" do %>
   <%= text_field_tag 'search', nil, :placeholder => "Enter ISBN Number here...." %>
   <%= submit_tag 'Search', :type => :image, :src => '/assets/searchicon.png' %>
   <% end %>
  </div>
 </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="row">
        <div id="left-menu" class="span3">
          <div class="side-nav sidebar-block">
           <h2>Categories</h2>
            <ul>
              <% @bookcategories.each do |b| %>
              <li><%= link_to b.name %></li>
             <% end %>
            </ul>
          </div>
        </div>
        <div class="span9">
          <h2><%= @book.bookname %></h2>
          <h5><b>Author</b>:&nbsp;<%= @book.author %></h5>
          <h5><b>Category</b>:&nbsp;<% if @book.category %><%= @book.category.name %><% end %></h5>
          <div class="row team-member">
          <div class="span2 photo">
            <div class="bordered-image">
              <% if @book.image %>
               <img src = <%= @book.image %>>
              <% else %>
               <%= image_tag @book.avatar.url(:medium) %>
              <% end %>
            </div>
          </div>
          <div class="span7">
            <p><%= raw(truncate(@book.description, :length => 1000, :omission => (link_to' (continued)', :id => 'revealMore'))) %></p>
            <% if @book.checked_out && @book.user.name == current_user.name  %>
             <p>You currently have this book</p>
            <% elsif %>
            <% if @book.user %>This book has been checked out by&nbsp;<%= @book.user.name %><% end %>
            <% else %>
             Available for checkout
            <% end %>
            <% if current_user.id == @book.user_id %>
            <%= render 'shared/checkin' %>
            <% elsif @book.checked_out == false %>
            <%= render 'shared/checkout' %>
            <% else %> 
            <%= render 'shared/registerinterest' %>
            <% end %>
          </div>
        </div>
       </div>
      </div><!--/row-->
    </div><!--/span12-->
  </div><!--/row-->
</div><!--/container-->

app/views/categories/index.html.erb
<div class="container">
  <div class="row ">
    <div class="span12">     
      <% @categorisedbooks.each do |c| %>
      <%= image_tag c.avatar.url(:medium), :class=> "allBooksCover" %>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="row ">
    <div class="span12">     
      <% @categorisedbooks.each do |c| %>
      <img class="allBooksCover" src =<%= c.image %>>
      <% end %>
    </div>
  </div>
</div>

app/views/main/index.html.erb
<div class="container">
  <article>
  <div class="row">
		<div class="span6">
			<h2>Sign in to your Library Account</h2>
       <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
       <%= f.label :email %>
       <%= f.email_field :email %>
       <br>
       <%= f.label :password %>
       <%= f.password_field :password %>
       <br>
      <% if devise_mapping.rememberable? %>
      <%= f.label :remember_me %>
      <%= f.check_box :remember_me %>
      <% end %>

     <div><%= f.submit "Sign in", :class => 'button' %></div>
     <% end %>

     <%= render "devise/shared/links" %>
   </div>
    <div class="span6">
      <h2>Welcome to your Digital Library</h2>
       <p>Library Clerk is a Free Applicaiton that allows you to keep track of your Business Library and see who exactly has your assets.As well as keeping track of your library it allows a convienient wayu for your employees to check out a book and then check it back in without the need of manually filling in paperwork.</p>
       <p>On top of all this your employees can set reminders on books that are checked out, and then recieve an email when that book is checked back in, again no need for human intervention. If you feel that this could benefit your organisation then feel free to sign up and start your own digital library.</p>
       <p>
       <a class="m-btn blue" href="#">Read More</a>
      </p>
    </div>
	</div>
  </article>
</div>
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="row show-grid hero-list">
       <div class="span3">
        <div class="image-wrapper">
         <img src="/assets/ruler.png" alt="">
        </div>
          <h2>Clean Design</h2>
          <p>Modern, clean design to blend in with your business, a highly professional appearance.</p>
        </div>
         <div class="span3">
          <div class="image-wrapper">
           <img src="/assets/equaliser.png" alt="">
          </div>
           <h2>Administrator</h2>
            <p>Be the administrator for your Library and stay in control of your assets</p>
         </div>
          <div class="span3">
           <div class="image-wrapper">
            <img src="/assets/direction.png" alt="">
           </div>
            <h2>Quick Shortcuts</h2>
            <p>Dozens of unique shortcuts to add your own cool and custom flare.</p>
          </div>
           <div class="span3">
            <div class="image-wrapper">
             <img src="/assets/both_arrows.png" alt="">
            </div>
             <h2>Responsive</h2>
             <p>Ultra-responsive design so you can check the status of your library on practically any device.</p>
           </div>
   </div>
  </div>
 </div>
</div>

<div class="container">
  <article>
  <div class="row">
    <div class="span12">
      <h2> Who Uses Us</h2>
      <div class="row">
        <div class="span3">
          <img src="http://placehold.it/200x180">

        </div>

        <div class="span3">
         <img src="http://placehold.it/200x180">
        </div>

        <div class="span3">
         <img src="http://placehold.it/200x180">
        </div>

        <div class="span3">
          <img src="http://placehold.it/200x180">
        </div>


      </div>
    </div>
  </div>
</article>
</div>

app/views/members/my_books.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="row">
        <div id="left-menu" class="span3">
          <div class="side-nav sidebar-block">
           <h2>Categories</h2>
            <ul>
              <% @mycategories.each do |u| %>
              <li><%= link_to u.name %></li>
             <% end %>
            </ul>
          </div>
        </div>
        <div class="span9">       
         <div class="row">
          <% @book.each do |b| %>
           <div class= "span3 allBooks">
            <p><%= link_to truncate(b.bookname, :length => 33), b %></p>
             <img class="allBooksCover" src =<%= b.image %>>
           </div><!--span3-->
          <% end %>
        </div>
      </div>



      </div>
    </div>
  </div>
</div>

app/views/search/index.html.erb
<h1>User landing page</h1>

<%= link_to('Sign out', destroy_user_session_path, :confirm => 'Are you sure you want to log out',  :method => :delete) %>